feature: add step to deploy in production
e-cordel/ecordel-restapi pull request #32
Opened 2022-05-15 12:43 UTC by regisfbrilhante

# Description
This PR add a new step to deploy jar artifact into production

# Changes
 - Add a new step into pipeline
 - Add Elastic Beanstalk configs

2022-05-15 13:45 UTC, itsmemarioss requested changes
Nice one. 👍🏼 

Dois pontos que precisam ser mudados.

1. A action não executou no pr e parece haver um erro de sintaxe no yaml (https://github.com/e-cordel/ecordel-restapi/actions/runs/2327251453) 
2. Temos alterar a action para não ser executada em PRs. Se a action não tivesse falhado, esse pr teria substituído a aplicação em prod.

Minha sugestão para o ponto dois é reutilizar a action [new-pr.yml](https://github.com/e-cordel/ecordel-restapi/blob/cd9c1f24c3b8edac431c7f555131ad8741bc834a/.github/workflows/new-pr.yml) e adicionar os steps de build e static analysis.
Para action atual deve-se remover o `on push develop` e `on pull request`.

2022-05-15 13:46 UTC, itsmemarioss commented on .github/workflows/build.yml
> +        use: aws-actions/configure-aws-credentials@v1
typo: `use`
```suggestion
        uses: aws-actions/configure-aws-credentials@v1
```

2022-05-15 13:48 UTC, karloskelvinsantos approved these changes

2022-06-01 21:59 UTC, karloskelvinsantos approved these changes

2022-06-01 22:01 UTC, karloskelvinsantos approved these changes

2022-06-02 21:55 UTC, merged