feature/upgrade-spring-and-java
e-cordel/ecordel-restapi pull request #57
Opened 2024-05-11 17:19 UTC by karloskelvinsantos

# Upgrade Spring and Java.

Upgrade Spring boot to 3.2.5 and Java to 21.

what was changed?

- upgrade version spring boot parent to 3.2.5.
- adjusted on Spring Security configurations.
- adjusted some classes with sonarLint report correction. upgrade jdk to 21.
- adjusted all configs to consider java 21.

2024-05-12 15:50 UTC, itsmemarioss reviewed
LGTM
Deixei alguns comentários que não são críticos. Vou ainda instalar o java 21 e testar do meu lado. Depois aprovo.

2024-05-12 15:50 UTC, itsmemarioss commented on openapi.yaml
> +  version: "1.6.0"
Tenho dúvidas nessa alteração, apesar de não haver impacto algum.
A versão da spec não necessariamente é a mesma do pom, a interface pública continua igual o que mudou na verdade foi uma questão técnica que nada afeta o openapi. Eu deixaria com está. A não ser que tenha uma motivação mais forte.

2024-05-12 15:50 UTC, itsmemarioss commented on src/main/java/br/com/itsmemario/ecordel/security/CordelUser.java
> +    @Id
Essa identação parece estranha. É provável que tenhamos tabs diferentes. Depois podemos pensar em configurar um checkstyle.

2024-05-12 15:50 UTC, itsmemarioss commented on src/main/java/br/com/itsmemario/ecordel/security/TokenDto.java
> +public record TokenDto(String token, String authenticationMethod, Long expiresAt) {
Nice!

2024-05-12 21:27 UTC, karloskelvinsantos commented on openapi.yaml
> +  version: "1.6.0"
Então, eu pensei que esse version era associado a versão do pom mesmo.

Podemos realizar o rollback. De fato na estrutura da api não houve mudanças.

2024-05-12 21:28 UTC, karloskelvinsantos commented on src/main/java/br/com/itsmemario/ecordel/security/CordelUser.java
> +    @Id
Cara, não u vi isso kkkk. Mas na minha IDE não tá com essa identação.
Podemos adotar um prettier aí, para padronizar a parada.

2024-05-18 12:58 UTC, karloskelvinsantos commented on openapi.yaml
> +  version: "1.6.0"
Realizei o rollback.

2024-05-19 09:14 UTC, itsmemarioss requested changes
É preciso atualizar o `system.properties` também.

2024-05-19 09:41 UTC, itsmemarioss commented on src/main/java/br/com/itsmemario/ecordel/security/CordelUser.java
> +    @Id
Fazemos isso em um pr separado 👍🏼

2024-05-20 03:13 UTC, karloskelvinsantos commented
Done.

2024-05-23 20:10 UTC, itsmemarioss approved these changes

2024-05-23 20:10 UTC, merged