moving JwtToken to database
e-cordel/ecordel-restapi pull request #8
Opened 2021-04-25 19:01 UTC by JDanielT

# Pull Request Title

moving jwt token to database

what was changed?

 - creating jwt token table
 - injecting jwt token in AuthenticationService class

2021-04-29 05:18 UTC, halkernel commented
nice, thank you.

2021-04-29 05:18 UTC, halkernel approved these changes

2021-04-30 21:23 UTC, itsmemarioss requested changes
Massa @JDanielT. Deixei só um comentário sobre as configurações. Vou mudar o target do teu pr para uma feature branch ao invés da develop, porque assim podemos ver a execução do sonarcloud antes de fazer merge para dev. 

Obrigado 👍🏼

2021-04-30 21:23 UTC, itsmemarioss commented on src/main/java/br/com/itsmemario/ecordel/EcordelApplication.java
> +
Pode mover essas configurações de `@Bean` para a classe `SecurityConfig`? Assim mantemos as configurações de um mesmo contexto juntas na mesma classe.

2021-05-01 08:49 UTC, itsmemarioss reviewed
A ideia de termos a secret key no bd é permitir a mudança delas sem impacar os outros tokens que já foram gerados, ou até mesmo invalidar todos os tokens gerados com uma secred key que tenha vazado por exemplo. Da forma que está continuaríamos como o problema de não puder alterar o token on the fly. Podemos decidir se fazemos isso agora ou se registramos outra task para isso. Vale lembrar que essa não é uma feature prioritária mas melhoraria a seguraça da api. 

@e-cordel/core o que acham?

2021-05-01 08:49 UTC, itsmemarioss commented on src/main/java/br/com/itsmemario/ecordel/security/AuthenticationService.java
>  			.compact();
Aqui acho que deveríamos adicionar no JWT o header `kid` para sabermos qual token foi utilizado para construir o jwt.

https://tools.ietf.org/html/rfc7515#section-4.1.4

2021-05-01 08:49 UTC, itsmemarioss commented on src/main/java/br/com/itsmemario/ecordel/security/AuthenticationService.java
>  		}catch(io.jsonwebtoken.SignatureException e) {
O caso inverso do comentário anterior funcionaria aqui. Primeiro deveríamos ir ao header do token buscar o `kid` e verificar se esse token existe. Se existir trazemos o token do banco e usamos a secret key.

2021-05-07 17:12 UTC, JDanielT commented
Como ficou essa task, foi refinada? @itsmemarioss

2021-05-07 18:02 UTC, itsmemarioss commented
> Como ficou essa task, foi refinada? @itsmemarioss

@JDanielT então como eu te disse quando conversamos no ínicio, vc pegou uma task que não estava no ready :D então provavelmente pode faltar alguma coisa. Podemos refinar essa task na próxima reunião e vamos evoluindo em uma feature branch. É como preferir. Podemos também diminuir o escopo e ir aprovando prs menores.

2021-05-07 18:27 UTC, JDanielT commented
tranquilo @itsmemarioss. Vou aguardar o refinamento

2021-06-20 10:28 UTC, itsmemarioss commented
Vou aprovar esse pr para a feature branch, no entanto será necessário fazer rebase da feature branch uma vez que já entraram outros commits em master. 👍🏼 Obrigado pela contribuição @JDanielT

2021-06-20 10:29 UTC, merged